// <auto-generated />
using System;
using AILifeAnalytics.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AILifeAnalytics.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260324085323_AddCbtRecords")]
    partial class AddCbtRecords
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AILifeAnalytics.Domain.Entities.Activity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("FocusLevel")
                        .HasColumnType("integer");

                    b.Property<string>("HighlightsOfDay")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("Mood")
                        .HasColumnType("integer");

                    b.Property<string>("MoodReason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<double>("SleepHours")
                        .HasColumnType("double precision");

                    b.Property<int>("StressLevel")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<double>("WorkHours")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Date")
                        .IsUnique();

                    b.ToTable("Activities");
                });

            modelBuilder.Entity("AILifeAnalytics.Domain.Entities.CbtRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AdditionalEmotions")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AiChallenge")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("AiQuestions")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AiSummary")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("AutomaticThought")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Behavior")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DetectedDistortions")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("EmotionIntensity")
                        .HasColumnType("integer");

                    b.Property<string>("EvidenceAgainst")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EvidenceFor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Insight")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean");

                    b.Property<int>("NewEmotionIntensity")
                        .HasColumnType("integer");

                    b.Property<int>("NewThoughtBelief")
                        .HasColumnType("integer");

                    b.Property<string>("PhysicalState")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PrimaryEmotion")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("ReframedThought")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Situation")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("ThoughtBelief")
                        .HasColumnType("integer");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "CreatedAt");

                    b.ToTable("CbtRecords");
                });

            modelBuilder.Entity("AILifeAnalytics.Domain.Entities.Insight", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AnalysisType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<double>("BurnoutRisk")
                        .HasColumnType("double precision");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("ProductivityScore")
                        .HasColumnType("double precision");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Insights");
                });

            modelBuilder.Entity("AILifeAnalytics.Domain.Entities.PersonalityProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ArchetypeDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ArchetypeEmoji")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ArchetypeName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<double>("CorrelationSleepFocus")
                        .HasColumnType("double precision");

                    b.Property<double>("CorrelationStressMood")
                        .HasColumnType("double precision");

                    b.Property<int>("DaysAnalyzed")
                        .HasColumnType("integer");

                    b.Property<string>("EnergyPattern")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ForecastRisk")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ForecastText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullAnalysis")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("character varying(5000)");

                    b.Property<DateTime>("GeneratedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MostProductiveDayOfWeek")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("OptimalSleepHours")
                        .HasColumnType("double precision");

                    b.Property<double>("OptimalWorkHours")
                        .HasColumnType("double precision");

                    b.Property<string>("PeakPerformancePattern")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("PeriodFrom")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("PeriodTo")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Recommendations")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StressPattern")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Superpowers")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Vulnerabilities")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "GeneratedAt");

                    b.ToTable("PersonalityProfiles");
                });

            modelBuilder.Entity("AILifeAnalytics.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("AILifeAnalytics.Domain.Entities.UserSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ActiveProvider")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("DeepSeekKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("FocusGoal")
                        .HasColumnType("double precision");

                    b.Property<string>("GoogleAIKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HuggingFaceKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("MoodGoal")
                        .HasColumnType("double precision");

                    b.Property<string>("OpenAIKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("ProxyEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("ProxyHost")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProxyPassword")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ProxyPort")
                        .HasColumnType("integer");

                    b.Property<string>("ProxyUsername")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("SleepGoal")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserSettings");
                });

            modelBuilder.Entity("AILifeAnalytics.Domain.Entities.Activity", b =>
                {
                    b.HasOne("AILifeAnalytics.Domain.Entities.User", "User")
                        .WithMany("Activities")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("AILifeAnalytics.Domain.Entities.CbtRecord", b =>
                {
                    b.HasOne("AILifeAnalytics.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("AILifeAnalytics.Domain.Entities.Insight", b =>
                {
                    b.HasOne("AILifeAnalytics.Domain.Entities.User", "User")
                        .WithMany("Insights")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("AILifeAnalytics.Domain.Entities.PersonalityProfile", b =>
                {
                    b.HasOne("AILifeAnalytics.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("AILifeAnalytics.Domain.Entities.UserSettings", b =>
                {
                    b.HasOne("AILifeAnalytics.Domain.Entities.User", "User")
                        .WithOne("Settings")
                        .HasForeignKey("AILifeAnalytics.Domain.Entities.UserSettings", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("AILifeAnalytics.Domain.Entities.User", b =>
                {
                    b.Navigation("Activities");

                    b.Navigation("Insights");

                    b.Navigation("Settings");
                });
#pragma warning restore 612, 618
        }
    }
}
